### ISSUE TITLE
想请问一下安装环境的问题?

### ISSUE THREAD

**Issue by ChaosOrLight** [lunan0320/FedPHE#2]
作者您好，我是一名研究联邦学习的学生，我照着requirement.txt中的套件安装，但是一直卡在gap-stat这个套件一直报错，想请问一下有什么解决方式吗
![螢幕擷取畫面 2024-07-18 165005](https://github.com/user-attachments/assets/44c9725e-a803-4479-92be-a8d92f25f9d2)
![螢幕擷取畫面 2024-07-18 165144](https://github.com/user-attachments/assets/be36481a-0b10-485d-a449-0fe440edab6f)

**Comment by lunan0320** [comment]
您好，这个源代码库作者好像不再维护了，应该是版本的问题。
- 您如果仍然想做 client selection，可以在这个地址直接安装源文件 https://github.com/milesgranger/gap_statistic
- 您如果只是想做同态加密部分，那这一块是不影响的，您可以忽略。

**Comment by ChaosOrLight** [comment]
感谢作者回复，额外请教您一个问题，在研究此专案时，有发现到local node上传给server上使用的是参数，不过我查阅一些有关fl的文献通常上传的都是梯度，而一般不管实作或是主流的框架上传的都是参数，想请问有什么差异或是实作上的考量?

**Comment by lunan0320** [comment]
您好，上传参数和梯度都是可以的，上传梯度是为了保护隐私信息不被泄露，但现在通常认为上传梯度仍是有隐私泄露的风险，会使用一些额外的隐私保护技术。本文的方案使用的全同态加密来保护隐私，上传参数也能够保证密态聚合。
此外，一般情况下，上传参数更加直接，可能比梯度会有更好的表现，所以在有加密保护的情况下，本文传递了参数。
希望对您有所帮助！

**Comment by ChaosOrLight** [comment]
谢谢你的回答，不好意思，刚接触这个领域，有些资讯还不太了解，目前正打算研究梯度安全相关的方向，有看了几篇梯度相关的文献，所以想说可以实作使用梯度上传的方式。

**Comment by lunan0320** [comment]
不客气
