### ISSUE TITLE
Unable to run?

### ISSUE THREAD

**Issue by mohammadm147** [lunan0320/FedPHE#3]
I am trying to run an experiment, but I am getting the following error:
(FedPHE) C:\Users\moham\Downloads\Fed\FedPHE>python main.py --dataset MNIST --epochs 100 --lr 0.001 --n_clients 8 --topk 0.1 --algorithm ckks --enc_batch_size 4096 --sim_len 200
Traceback (most recent call last):
  File "C:\Users\moham\Downloads\Fed\FedPHE\main.py", line 11, in <module>
    from fed import run
  File "C:\Users\moham\Downloads\Fed\FedPHE\fed.py", line 10, in <module>
    from server import server_process
  File "C:\Users\moham\Downloads\Fed\FedPHE\server.py", line 12, in <module>
    from utils.draw import draw_acc,draw_participation
ModuleNotFoundError: No module named 'utils.draw'

Is there a dependency I am supposed to install that isn't included in the requirements file?

**Comment by lunan0320** [comment]
Sorry! The issue is that I didn't upload the necessary files for drawing when I uploaded the code. You can comment out the drawing-related code to run the project. I'll update it when I have time later.
