### ISSUE TITLE
请问如何修改命令行参数，以执行论文中的几个基准示例？

### ISSUE THREAD

**Issue by FHE027** [lunan0320/FedPHE#4]
论文中的Table 3给出了Plaintext/BatchCrypt/PackedBFV/PackedCKKS/FedPHE几种基准进行实验对比。在read.me中，作者给出了python main.py --dataset MNIST --epochs 100 --lr 0.001 --n_clients 8 --topk 0.1 --algorithm ckks --enc_batch_size 4096 --sim_len 200 --enc True --isSelection True --isSpars topk的执行示例，请问：
1.如果要验证第一种基准Plaintext，应该怎么修改上述的执行指令？
2.如果要验证paillier/bfv/ckks三种基准，是否要将--isSelection True --isSpars topk设为false或者randk？
3.如果要验证本文的FedPHE基准，应该怎么修改上述的执行指令？
4.在我输入执行指令中，设置--enc False，并且在代码中设置default=false，但Anconda界面中的basic information仍然提示isEnc ture。请问该如何解决？

期待您的指导和帮助，谢谢！

**Comment by lunan0320** [comment]
感谢您对本项目的关注
1、测试 plaintext，修改 `--enc Fasle --isSelection False`
2、测试三个基准，修改 `--algorithm paillier/bfv/ckks --isSelection False`
3、测试FedPHE基准，项目中已经给出具体的示例 `python main.py --dataset MNIST --epochs 100 --lr 0.001 --n_clients 8 --topk 0.1 --algorithm ckks --enc_batch_size 4096 --sim_len 200 --enc True --isSelection True --isSpars topk`
4、设置 `parser.add_argument('--enc',type=bool,default=False, help='enc or not')`

**Comment by jingluo168** [comment]
> 论文中的Table 3给出了Plaintext/BatchCrypt/PackedBFV/PackedCKKS/FedPHE几种基准进行实验对比。在 read.me 中，作者给出了python main.py --dataset MNIST --epochs 100 --lr 0.001 --n_clients 8 --topk 0.1 --algorithm ckks --enc_batch_size 4096 --sim_len 200 --enc True --isSelection True --isSpars topk的执行示例，请问： 1.如果要验证第一种基准Plaintext，应该怎么修改上述的执行指令？ 2.如果要验证paillier/bfv/ckks三种基准，是否要将--isSelection True --isSpars topk设为false或者randk？3.如果要验证本文的FedPHE基准，应该怎么修改上述的执行指令？ 4.在我输入执行指令中，设置--enc False，并且在代码中设置default=false，但Anconda界面中的basicinformation仍然提示isEnc ture。请问该如何解决？
> 
> 期待您的指导和帮助，谢谢！

您好，请问你，这个基准测试。你解决了吗？这个没有懂是什么意思

![Image](https://github.com/user-attachments/assets/fff2f1ef-e1b2-4a54-bba7-736d4a28c9b8)
